# Generated by Django 3.1.7 on 2022-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='measurementunits',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
