# Generated by Django 3.1.7 on 2022-03-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20220306_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingheader',
            name='box',
            field=models.IntegerField(default=1),
        ),
    ]
